# Setup
title:               kazuhironx's tech blog
tagline:             '日々のメモ置き場'
description:         'xxxx yyyy zzzz'
url:                 https://kazuhironx.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              kazuhironx
  url:               https://kazuhironx.github.io
  email:             kazuhironxATgmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
